### ISSUE TITLE
10.10 broke swizzling?

### ISSUE THREAD

**Issue by numist** [numist/NNKit#17]
Unit tests are failing after upgrade to 10.10/Xcode 6:

    Test Suite 'NNKit Mac Tests.xctest' failed at 2015-03-03 05:32:51 +0000.
      Executed 56 tests, with 25 failures (0 unexpected) in 0.284 (0.313) seconds
    Test Suite 'All tests' failed at 2015-03-03 05:32:51 +0000.
      Executed 56 tests, with 25 failures (0 unexpected) in 0.284 (0.315) seconds
    Failing tests:
      -[NNStrongifiedPropertiesTests testSwizzledBasicStrongGetter]
      -[NNStrongifiedPropertiesTests testSwizzledCapitalizedStrongGetter]
      -[NNStrongifiedPropertiesTests testSwizzledNilling]
      -[nn_isaSwizzlingTests testAddsLegalProperties]
      -[nn_isaSwizzlingTests testAddsLegalProperties]
      -[nn_isaSwizzlingTests testDoubleSwizzle]
      -[nn_isaSwizzlingTests testDoubleSwizzle]
      -[nn_isaSwizzlingTests testDoubleSwizzle]
      -[nn_isaSwizzlingTests testDoubleSwizzle]
      -[nn_isaSwizzlingTests testDoubleSwizzle]
      -[nn_isaSwizzlingTests testDoubleSwizzle]
      -[nn_isaSwizzlingTests testExtraProtocol]
      -[nn_isaSwizzlingTests testExtraProtocol]
      -[nn_isaSwizzlingTests testExtraProtocol]
      -[nn_isaSwizzlingTests testGood]
      -[nn_isaSwizzlingTests testGood]
      -[nn_isaSwizzlingTests testGood]
      -[nn_isaSwizzlingTests testGood]
      -[nn_isaSwizzlingTests testGood]
      -[nn_isaSwizzlingTests testGood]
      -[nn_isaSwizzlingTests testImplementationDetails]
      -[nn_isaSwizzlingTests testImplementationDetails]
      -[nn_isaSwizzlingTests testImplementationDetails]
      -[nn_isaSwizzlingTests testNoProto]
      -[nn_isaSwizzlingTests testSharedAncestor]
    ** TEST FAILED **

**Comment by thekarladam** [comment]
I hope so?

**Comment by numist** [comment]
Looks like the runtime quietly added some new properties to `NNISASwizzledObject`:

    2015-03-04 22:11:40.129 xctest[33169:3166898] Swizzling class NNISASwizzledObject cannot contain non-dynamic properties
    (lldb) p (char *)property_getName(properties[0])
    (char *) $0 = 0x000000010071b59f "hash"
    (lldb) p (char *)property_getName(properties[1])
    (char *) $1 = 0x000000010071b5f6 "superclass"
    (lldb) p (char *)property_getName(properties[2])
    (char *) $2 = 0x000000010071b606 "description"
    (lldb) p (char *)property_getName(properties[3])
    (char *) $3 = 0x000000010071b623 "debugDescription"

They're not in the class' declaration or extension, but they are in `class_copyPropertyList`. How is this code supposed to determine stuff the user wrote vs stuff that the runtime is adding?

**Comment by thekarladam** [comment]
This code being yours or Apple's? Those methods, aside from debugDescription, are documented parts of the NSObject protocol. Maybe they're just claiming their own.

**Comment by numist** [comment]
`class_copyPropertyList` is documented to only return properties specific to that class. Those methods are both inherited (not overridden) and not properties.

Definitely looks like a runtime bug. Disabling the dynamic property check and falling back to `class_replaceProperty` when `class_addProperty` fails allows all the unit tests to pass again.

**Comment by numist** [comment]
CI failed for [build 24](https://travis-ci.org/numist/NNKit/builds/53224828), but I have no idea what version of OS X or Xcode `saucelabs-mac-1.worker.travis-ci.org:travis-mac_osx-13` is using.

Without a reliable SDK check (AppKit doesn't seem to have published a `NSAppKitVersionNumber10_10` anywhere), it's best to just disable the property check outright.

**Comment by gparker42** [comment]
These properties appear in class NNISASwizzledObject because that class conforms to protocol NNISASwizzledObject which conforms to protocol NSObject which declares these properties.

**Comment by numist** [comment]
@gparker42: Those properties don't have backing ivars, shouldn't they have the dynamic attribute?

This makes it a lot harder to determine whether a protocol is defined by a class or declared by its ancestry when using `class_copyPropertyList`.

**Comment by numist** [comment]
Actually, what was more concerning to me was that `class_addProperty` was failing on a [class that had just been created by `objc_allocateClassPair`](https://github.com/numist/NNKit/blob/master/NNKit/Swizzling/nn_isaSwizzling.m#L139). Shouldn't a class allocated by that function arrive empty of properties?
